version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: "no"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/
      - MONGODB_HOST=db
      - SIMPLE_LOG=True
    ports:
      - "5000:5000"

  db:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
volumes:
  data: